### PR TITLE
Update otj-parent-spring version

### PR DESCRIPTION
**Pull request by SegFaultAX**
* Add gitignore for Java language and JetBrains IDEs

### CODE REVIEW

**Comment by rushalias** [comment]
updated the pom to version 84 & now mvn clean install is failing 
```

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/ltahmazyan/IdeaProjects/service-buzzsaw/service/src/main/java/com/opentable/buzzsaw/service/MessageSource.java:[77,39] incompatible types: org.apache.kafka.common.TopicPartition[] cannot be converted to java.util.Collection<org.apache.kafka.common.TopicPartition>
[ERROR] /Users/ltahmazyan/IdeaProjects/service-buzzsaw/service/src/main/java/com/opentable/buzzsaw/service/MessageSource.java:[88,40] incompatible types: org.apache.kafka.common.TopicPartition[] cannot be converted to java.util.Collection<org.apache.kafka.common.TopicPartition>
[ERROR] /Users/ltahmazyan/IdeaProjects/service-buzzsaw/service/src/main/java/com/opentable/buzzsaw/service/MessageSource.java:[106,28] incompatible types: org.apache.kafka.common.TopicPartition[] cannot be converted to java.util.Collection<org.apache.kafka.common.TopicPartition>
[ERROR] /Users/ltahmazyan/IdeaProjects/service-buzzsaw/service/src/main/java/com/opentable/buzzsaw/service/MessageSource.java:[109,29] incompatible types: org.apache.kafka.common.TopicPartition[] cannot be converted to java.util.Collection<org.apache.kafka.common.TopicPartition>
[INFO] 4 errors

...

[INFO] buzzsaw-parent ..................................... SUCCESS [  3.360 s]
[INFO] buzzsaw ............................................ SUCCESS [ 14.995 s]
[INFO] buzzsaw-service .................................... FAILURE [  0.845 s]
```

**Comment by SegFaultAX** [comment]
@rushalias That error is precisely what this PR fixes. The problem is the current release of otj-kafka references otj-parent-spring 83 which is unresolvable. So updating buzzsaw to parent 84 brings in otj-kafka 2.0.0-alpha0 which references an unresolvable parent pom. :(

**Comment by SegFaultAX** [comment]
Ref: https://github.com/opentable/otj-parent/commit/ad86eb8c0deb9fe3562df8d8cba439b581013bbd

**Comment by rushalias** [comment]
My bad!

**Pull request merged**
